GET http://localhost:4000/users

###

POST http://localhost:4000/login/register
Content-Type: application/json

{

    "email" : "kshitij",
    "username" : "Nikhil",
    "password" : "abcdefg"
}

###

POST http://localhost:4000/login/loginuser
Content-Type: application/json

{

    "username" : "Manish",
    "password" : "Manish@123"
}

###

GET http://localhost:4000/printHello
Authorization:Bearer eyghbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc5ODkwNjB9.JAG_vje-3qC0Vf8ElBpHyKEUZUspJq9f-N9X3zZqTHk


###

POST http://localhost:4000/splogin/registerSP
Content-Type: application/json

{
    "username":"Manish",
    "password":"Manish@123",
    "email":"manish@123",
    "servname":"plumber",
    "pno":null
}

###

POST http://localhost:4000/splogin/loginSP
Content-Type: application/json

{
    "username":"Manish",
    "password":"Manish@123"
}

###

POST http://localhost:4000/serviceproviders/updateDetails/addSubService
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFuaXNoIiwiaWF0IjoxNjI4NTM4MDc4fQ.b9FzMtuKYfvW3YI6L48HIEyO8Rk4spMuasprzbeMUaw
Content-Type: application/json

{
    "newService" : {"name":"door","cost":"5000","days":"5"}
}


###

POST http://localhost:4000/adminlogin/registeradmin
Content-Type: application/json

{

    "email" : "manish@gmail.com",
    "username" : "Manish",
    "password" : "Manish@123",
    "pno" : "123456789"
}
