GET http://localhost:4000/users

###

POST http://localhost:4000/login/register
Content-Type: application/json

{

    "email" : "kshitij",
    "username" : "Nikhil",
    "password" : "abcdefg"
}

###

POST http://localhost:4000/login/loginuser
Content-Type: application/json

{

    "username" : "Manish",
    "password" : "Manish@123"
}

###

GET http://localhost:4000/printHello
Authorization:Bearer eyghbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc5ODkwNjB9.JAG_vje-3qC0Vf8ElBpHyKEUZUspJq9f-N9X3zZqTHk